// source: agent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.AWS.SageMaker.Edge.CaptureDataRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.AWS.SageMaker.Edge.AuxilaryData');
goog.require('proto.AWS.SageMaker.Edge.Tensor');
goog.require('proto.AWS.SageMaker.Edge.Timestamp');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AWS.SageMaker.Edge.CaptureDataRequest.repeatedFields_, null);
};
goog.inherits(proto.AWS.SageMaker.Edge.CaptureDataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AWS.SageMaker.Edge.CaptureDataRequest.displayName = 'proto.AWS.SageMaker.Edge.CaptureDataRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.repeatedFields_ = [4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.AWS.SageMaker.Edge.CaptureDataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AWS.SageMaker.Edge.CaptureDataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    modelName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    captureId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    inferenceTimestamp: (f = msg.getInferenceTimestamp()) && proto.AWS.SageMaker.Edge.Timestamp.toObject(includeInstance, f),
    inputTensorsList: jspb.Message.toObjectList(msg.getInputTensorsList(),
    proto.AWS.SageMaker.Edge.Tensor.toObject, includeInstance),
    outputTensorsList: jspb.Message.toObjectList(msg.getOutputTensorsList(),
    proto.AWS.SageMaker.Edge.Tensor.toObject, includeInstance),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.AWS.SageMaker.Edge.AuxilaryData.toObject, includeInstance),
    outputsList: jspb.Message.toObjectList(msg.getOutputsList(),
    proto.AWS.SageMaker.Edge.AuxilaryData.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AWS.SageMaker.Edge.CaptureDataRequest;
  return proto.AWS.SageMaker.Edge.CaptureDataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AWS.SageMaker.Edge.CaptureDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaptureId(value);
      break;
    case 3:
      var value = new proto.AWS.SageMaker.Edge.Timestamp;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.Timestamp.deserializeBinaryFromReader);
      msg.setInferenceTimestamp(value);
      break;
    case 4:
      var value = new proto.AWS.SageMaker.Edge.Tensor;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.Tensor.deserializeBinaryFromReader);
      msg.addInputTensors(value);
      break;
    case 5:
      var value = new proto.AWS.SageMaker.Edge.Tensor;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.Tensor.deserializeBinaryFromReader);
      msg.addOutputTensors(value);
      break;
    case 6:
      var value = new proto.AWS.SageMaker.Edge.AuxilaryData;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.AuxilaryData.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 7:
      var value = new proto.AWS.SageMaker.Edge.AuxilaryData;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.AuxilaryData.deserializeBinaryFromReader);
      msg.addOutputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AWS.SageMaker.Edge.CaptureDataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AWS.SageMaker.Edge.CaptureDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModelName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCaptureId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInferenceTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.AWS.SageMaker.Edge.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getInputTensorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.AWS.SageMaker.Edge.Tensor.serializeBinaryToWriter
    );
  }
  f = message.getOutputTensorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.AWS.SageMaker.Edge.Tensor.serializeBinaryToWriter
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.AWS.SageMaker.Edge.AuxilaryData.serializeBinaryToWriter
    );
  }
  f = message.getOutputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.AWS.SageMaker.Edge.AuxilaryData.serializeBinaryToWriter
    );
  }
};


/**
 * optional string model_name = 1;
 * @return {string}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getModelName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setModelName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string capture_id = 2;
 * @return {string}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getCaptureId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setCaptureId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Timestamp inference_timestamp = 3;
 * @return {?proto.AWS.SageMaker.Edge.Timestamp}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getInferenceTimestamp = function() {
  return /** @type{?proto.AWS.SageMaker.Edge.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.AWS.SageMaker.Edge.Timestamp, 3));
};


/**
 * @param {?proto.AWS.SageMaker.Edge.Timestamp|undefined} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
*/
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setInferenceTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.clearInferenceTimestamp = function() {
  return this.setInferenceTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.hasInferenceTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Tensor input_tensors = 4;
 * @return {!Array<!proto.AWS.SageMaker.Edge.Tensor>}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getInputTensorsList = function() {
  return /** @type{!Array<!proto.AWS.SageMaker.Edge.Tensor>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AWS.SageMaker.Edge.Tensor, 4));
};


/**
 * @param {!Array<!proto.AWS.SageMaker.Edge.Tensor>} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
*/
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setInputTensorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.AWS.SageMaker.Edge.Tensor=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AWS.SageMaker.Edge.Tensor}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.addInputTensors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.AWS.SageMaker.Edge.Tensor, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.clearInputTensorsList = function() {
  return this.setInputTensorsList([]);
};


/**
 * repeated Tensor output_tensors = 5;
 * @return {!Array<!proto.AWS.SageMaker.Edge.Tensor>}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getOutputTensorsList = function() {
  return /** @type{!Array<!proto.AWS.SageMaker.Edge.Tensor>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AWS.SageMaker.Edge.Tensor, 5));
};


/**
 * @param {!Array<!proto.AWS.SageMaker.Edge.Tensor>} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
*/
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setOutputTensorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.AWS.SageMaker.Edge.Tensor=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AWS.SageMaker.Edge.Tensor}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.addOutputTensors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.AWS.SageMaker.Edge.Tensor, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.clearOutputTensorsList = function() {
  return this.setOutputTensorsList([]);
};


/**
 * repeated AuxilaryData inputs = 6;
 * @return {!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AWS.SageMaker.Edge.AuxilaryData, 6));
};


/**
 * @param {!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
*/
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setInputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.AWS.SageMaker.Edge.AuxilaryData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AWS.SageMaker.Edge.AuxilaryData}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.AWS.SageMaker.Edge.AuxilaryData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.clearInputsList = function() {
  return this.setInputsList([]);
};


/**
 * repeated AuxilaryData outputs = 7;
 * @return {!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.getOutputsList = function() {
  return /** @type{!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AWS.SageMaker.Edge.AuxilaryData, 7));
};


/**
 * @param {!Array<!proto.AWS.SageMaker.Edge.AuxilaryData>} value
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
*/
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.setOutputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.AWS.SageMaker.Edge.AuxilaryData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AWS.SageMaker.Edge.AuxilaryData}
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.addOutputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.AWS.SageMaker.Edge.AuxilaryData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AWS.SageMaker.Edge.CaptureDataRequest} returns this
 */
proto.AWS.SageMaker.Edge.CaptureDataRequest.prototype.clearOutputsList = function() {
  return this.setOutputsList([]);
};


