// source: agent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.AWS.SageMaker.Edge.DescribeModelResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.AWS.SageMaker.Edge.Model');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AWS.SageMaker.Edge.DescribeModelResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AWS.SageMaker.Edge.DescribeModelResponse.displayName = 'proto.AWS.SageMaker.Edge.DescribeModelResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.AWS.SageMaker.Edge.DescribeModelResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AWS.SageMaker.Edge.DescribeModelResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    model: (f = msg.getModel()) && proto.AWS.SageMaker.Edge.Model.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AWS.SageMaker.Edge.DescribeModelResponse}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AWS.SageMaker.Edge.DescribeModelResponse;
  return proto.AWS.SageMaker.Edge.DescribeModelResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AWS.SageMaker.Edge.DescribeModelResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AWS.SageMaker.Edge.DescribeModelResponse}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.AWS.SageMaker.Edge.Model;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.Model.deserializeBinaryFromReader);
      msg.setModel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AWS.SageMaker.Edge.DescribeModelResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AWS.SageMaker.Edge.DescribeModelResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModel();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.AWS.SageMaker.Edge.Model.serializeBinaryToWriter
    );
  }
};


/**
 * optional Model model = 1;
 * @return {?proto.AWS.SageMaker.Edge.Model}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.getModel = function() {
  return /** @type{?proto.AWS.SageMaker.Edge.Model} */ (
    jspb.Message.getWrapperField(this, proto.AWS.SageMaker.Edge.Model, 1));
};


/**
 * @param {?proto.AWS.SageMaker.Edge.Model|undefined} value
 * @return {!proto.AWS.SageMaker.Edge.DescribeModelResponse} returns this
*/
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.setModel = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AWS.SageMaker.Edge.DescribeModelResponse} returns this
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.clearModel = function() {
  return this.setModel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AWS.SageMaker.Edge.DescribeModelResponse.prototype.hasModel = function() {
  return jspb.Message.getField(this, 1) != null;
};


