// source: agent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.AWS.SageMaker.Edge.ListModelsResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.AWS.SageMaker.Edge.Model');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AWS.SageMaker.Edge.ListModelsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AWS.SageMaker.Edge.ListModelsResponse.repeatedFields_, null);
};
goog.inherits(proto.AWS.SageMaker.Edge.ListModelsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AWS.SageMaker.Edge.ListModelsResponse.displayName = 'proto.AWS.SageMaker.Edge.ListModelsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.AWS.SageMaker.Edge.ListModelsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AWS.SageMaker.Edge.ListModelsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    modelsList: jspb.Message.toObjectList(msg.getModelsList(),
    proto.AWS.SageMaker.Edge.Model.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AWS.SageMaker.Edge.ListModelsResponse}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AWS.SageMaker.Edge.ListModelsResponse;
  return proto.AWS.SageMaker.Edge.ListModelsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AWS.SageMaker.Edge.ListModelsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AWS.SageMaker.Edge.ListModelsResponse}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.AWS.SageMaker.Edge.Model;
      reader.readMessage(value,proto.AWS.SageMaker.Edge.Model.deserializeBinaryFromReader);
      msg.addModels(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AWS.SageMaker.Edge.ListModelsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AWS.SageMaker.Edge.ListModelsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.AWS.SageMaker.Edge.Model.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Model models = 1;
 * @return {!Array<!proto.AWS.SageMaker.Edge.Model>}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.getModelsList = function() {
  return /** @type{!Array<!proto.AWS.SageMaker.Edge.Model>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AWS.SageMaker.Edge.Model, 1));
};


/**
 * @param {!Array<!proto.AWS.SageMaker.Edge.Model>} value
 * @return {!proto.AWS.SageMaker.Edge.ListModelsResponse} returns this
*/
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.setModelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.AWS.SageMaker.Edge.Model=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AWS.SageMaker.Edge.Model}
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.addModels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.AWS.SageMaker.Edge.Model, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AWS.SageMaker.Edge.ListModelsResponse} returns this
 */
proto.AWS.SageMaker.Edge.ListModelsResponse.prototype.clearModelsList = function() {
  return this.setModelsList([]);
};


